import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { lectures, notes } from "@/db/schema";
import { getSessionUser } from "@/lib/auth";
import { callGroq } from "@/lib/ai";

export async function POST(req: Request) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { lectureId } = await req.json();
  if (!lectureId) return NextResponse.json({ error: "lectureId required" }, { status: 400 });

  const lecture = await db.select().from(lectures).where(eq(lectures.id, lectureId)).limit(1);
  if (!lecture[0]) return NextResponse.json({ error: "Lecture not found" }, { status: 404 });

  const transcript = lecture[0].transcript || "";
  const title = lecture[0].title;

  const result = await callGroq([
    {
      role: "system",
      content: `You generate downloadable study notes in structured markdown. Format:

# ${title}

## 📋 Summary
[2-3 sentence summary]

## 🎯 Key Concepts
- [Concept 1]: [brief explanation]
- [Concept 2]: [brief explanation]
- [Concept 3]: [brief explanation]

## 📌 Important Points
1. [Point 1]
2. [Point 2]
3. [Point 3]

## 💡 Examples
- [Example 1]
- [Example 2]

## 🔗 Related Topics
- [Topic 1]
- [Topic 2]

## ✅ Action Items
- [ ] Review [topic]
- [ ] Practice [exercise]
- [ ] Complete quiz

---
*Generated by Arynox-EDU AI | Lecture: ${title}*`,
    },
    { role: "user", content: transcript ? `Title: ${title}\n\nTranscript:\n${transcript}` : `Title: ${title}\n\nGenerate comprehensive study notes.` },
  ], { temperature: 0.3 });

  if (!result.ok || !result.content) {
    return NextResponse.json({ error: result.error || "Notes generation failed" }, { status: 500 });
  }

  return NextResponse.json({ notes: result.content, title, lectureId });
}